# Generated by Django 4.0.3 on 2022-05-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jak', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
